/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 baju_atas.glb 
*/
"use client";
import { editable } from "@theatre/r3f";
import React, { act, useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function BajuModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/baju_atas.glb");
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      
      actions[names[0]]?.play();
    }
  }, [actions]);
  return (
    <group receiveShadow castShadow ref={group} {...props} dispose={null}>
      <editable.group castShadow receiveShadow theatreKey='baju_atas' name='Scene'>
        <mesh
          receiveShadow
          castShadow
          name='baju_atas'
          geometry={nodes.baju_atas.geometry}
          material={materials["Material.003"]}
          morphTargetDictionary={nodes.baju_atas.morphTargetDictionary}
          morphTargetInfluences={nodes.baju_atas.morphTargetInfluences}
          position={[0.023, 0.693, 0.086]}
          scale={0.981}
        ></mesh>
      </editable.group>
    </group>
  );
}

useGLTF.preload("/models/baju_atas.glb");
