/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kaos_kaki.glb 
*/
import { editable } from "@theatre/r3f";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function KaosKakiModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/kaos_kaki.glb");
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      actions[names[0]]?.play();
    }
  }, [actions]);
  return (
    <editable.group theatreKey='kaos_kaki' ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          castShadow
          name='kaos_kaki'
          geometry={nodes.kaos_kaki.geometry}
          material={materials.kaos_kaki_mat}
          morphTargetDictionary={nodes.kaos_kaki.morphTargetDictionary}
          morphTargetInfluences={nodes.kaos_kaki.morphTargetInfluences}
          position={[-0.002, 0.244, 0.047]}
          scale={0.837}
        />
      </group>
    </editable.group>
  );
}

useGLTF.preload("/models/kaos_kaki.glb");
