/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lengan.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { editable } from "@theatre/r3f";
export function LenganModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/lengan.glb");
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    if (actions) {
      actions[names[1]]?.play();
    }
  }, [actions]);
  return (
    <editable.group theatreKey='lengan' castShadow receiveShadow ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='lengan'>
          <mesh
            castShadow
            name='lengan_1'
            geometry={nodes.lengan_1.geometry}
            material={materials.lengan_mat}
            morphTargetDictionary={nodes.lengan_1.morphTargetDictionary}
            morphTargetInfluences={nodes.lengan_1.morphTargetInfluences}
            position={[0.027, 0.542, 0.178]}
            scale={1.03}
          />
        </group>
      </group>
    </editable.group>
  );
}

useGLTF.preload("/models/lengan.glb");
