/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/kaos.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function KaosModel(props) {
  const { nodes, materials } = useGLTF("/kaos.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["baju-mat"].geometry} material={materials["Material.002"]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  );
}

useGLTF.preload("/kaos.glb");
